In [1]:
import numpy as np

In [6]:
import plotly.express as px

In [2]:
def softmax(a:np.array):
    c = np.max(a)
    b = a-c
    a_exp = np.exp(b)
    sum_exp=np.sum(a_exp)
    return a_exp/sum_exp

In [16]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [17]:
y=softmax(a)

In [18]:
y

array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

In [19]:
y[1]-y[0],y[2]-y[1]

(0.055085715461947585, 0.14973849934787756)

In [22]:
fig=px.line(x=a,y=y)
fig.show()

In [59]:
z = np.arange(0.1,5,0.05)

In [60]:
f = lambda x:x*np.log(x)-x

In [61]:
f = lambda x:np.log(x)+1/x -1

In [62]:
y=f(z)

In [63]:
fig=px.line(x=z,y=y)
fig.show()

In [64]:
from sklearn.ensemble._gb_losses import HuberLossFunction

In [66]:
huber=_gb_losses.HuberLossFunction(0.9)

In [67]:
y=np.array([0.2,0.5,0.7])
y_pred=np.array([0.3,0.4,0.7])

In [68]:
huber.__call__(y,y_pred)

0.003333333333333332

In [114]:
z = np.arange(0,20,0.5)

# c = 17.55
c=np.round(np.percentile(z,90),2)

f1 = lambda x:np.power(x,2)/2  # MSE
f2 = lambda x,c: c * (x-c/2)  # MAE

x1 = z[z<=c]
x2=z[z>c]

y1 = f1(x1)
y2 = f2(x2,c)

17.55

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5])

In [93]:
y1,y2

(array([0.00000e+00, 1.25000e-01, 5.00000e-01, 1.12500e+00, 2.00000e+00,
        3.12500e+00, 4.50000e+00, 6.12500e+00, 8.00000e+00, 1.01250e+01,
        1.25000e+01, 1.51250e+01, 1.80000e+01, 2.11250e+01, 2.45000e+01,
        2.81250e+01, 3.20000e+01, 3.61250e+01, 4.05000e+01, 4.51250e+01,
        5.00000e+01, 5.51250e+01, 6.05000e+01, 6.61250e+01, 7.20000e+01,
        7.81250e+01, 8.45000e+01, 9.11250e+01, 9.80000e+01, 1.05125e+02,
        1.12500e+02, 1.20125e+02, 1.28000e+02, 1.36125e+02, 1.44500e+02,
        1.53125e+02]),
 array([161.89875, 170.67375, 179.44875, 188.22375]))

In [113]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

fig = make_subplots(rows=1, shared_xaxes=True,shared_yaxes=True,vertical_spacing=0.1)
fig.add_scatter(x=x1,y=y1,name='<=17.55')
fig.add_scatter(x=x2,y=y2,name='>17.55')
fig.show()

In [136]:
# y=0
f0 =  lambda x:np.exp(x)
# y=1
f1 = lambda x:np.exp(-x)

In [150]:
y = np.random.choice([0,1],50)
pred = np.linspace(-5,5,50)
y0=pred[y==0]
y1=pred[y==1]
z0=f0(y0)
z1=f1(y1)

In [151]:
fig = make_subplots(rows=1, shared_xaxes=True,shared_yaxes=True,vertical_spacing=0.1)
fig.add_scatter(x=y0,y=z0,name='y==0')
fig.add_scatter(x=y1,y=z1,name='y==1')
fig.show()

In [153]:
pred = np.linspace(0,5,50)
px.line(x=pred,y=pred)

In [154]:
x = np.linspace(-5,5,100)
f = lambda x:x**2 / 2

In [155]:
y=f(x)
px.line(x=x,y=y)

In [157]:
# y=0
f0 =  lambda x:-np.log(1+np.exp(x))
# y=1
f1 = lambda x:-2*x -np.log(1+np.exp(x))

In [158]:
y = np.random.choice([0,1],50)
pred = np.linspace(-5,5,50)
y0=pred[y==0]
y1=pred[y==1]
z0=f0(y0)
z1=f1(y1)

In [165]:
fig = make_subplots(rows=1, shared_xaxes=True,shared_yaxes=True,vertical_spacing=0.1)
fig.add_scatter(x=y0,y=z0,name='y==0')
fig.add_scatter(x=y1,y=z1,name='y==1')
fig.show()

In [166]:
x=np.linspace(-5,5,50)

In [167]:
f1 = lambda x:-x * (1-q)
# > 0 
f2 = lambda x: x*q

In [168]:
q=0.3
y1 = f1(x[x<0])
y2 = f2(x[x>=0])

In [169]:
y = np.concatenate([y1,y2])

In [171]:
q=0.7
y1 = f1(x[x<0])
y2 = f2(x[x>=0])

In [172]:
yn = np.concatenate([y1,y2])

In [173]:
fig = make_subplots(rows=1, shared_xaxes=True,shared_yaxes=True,vertical_spacing=0.1)
fig.add_scatter(x=x,y=y,name='q==0.3')
fig.add_scatter(x=x,y=yn,name='q==0.7')
fig.show()

In [175]:
import xgboost

In [178]:
xgboost.XGBRegressor

xgboost.sklearn.XGBModel

In [179]:
xg=xgboost.XGBRegressor()
xg.get_params()

{'objective': 'reg:squarederror',
 'base_score': None,
 'booster': None,
 'callbacks': None,
 'colsample_bylevel': None,
 'colsample_bynode': None,
 'colsample_bytree': None,
 'early_stopping_rounds': None,
 'enable_categorical': False,
 'eval_metric': None,
 'feature_types': None,
 'gamma': None,
 'gpu_id': None,
 'grow_policy': None,
 'importance_type': None,
 'interaction_constraints': None,
 'learning_rate': None,
 'max_bin': None,
 'max_cat_threshold': None,
 'max_cat_to_onehot': None,
 'max_delta_step': None,
 'max_depth': None,
 'max_leaves': None,
 'min_child_weight': None,
 'missing': nan,
 'monotone_constraints': None,
 'n_estimators': 100,
 'n_jobs': None,
 'num_parallel_tree': None,
 'predictor': None,
 'random_state': None,
 'reg_alpha': None,
 'reg_lambda': None,
 'sampling_method': None,
 'scale_pos_weight': None,
 'subsample': None,
 'tree_method': None,
 'validate_parameters': None,
 'verbosity': None}

In [181]:
len(xg.get_params().keys())

39

In [182]:
xg.get_params().keys()

dict_keys(['objective', 'base_score', 'booster', 'callbacks', 'colsample_bylevel', 'colsample_bynode', 'colsample_bytree', 'early_stopping_rounds', 'enable_categorical', 'eval_metric', 'feature_types', 'gamma', 'gpu_id', 'grow_policy', 'importance_type', 'interaction_constraints', 'learning_rate', 'max_bin', 'max_cat_threshold', 'max_cat_to_onehot', 'max_delta_step', 'max_depth', 'max_leaves', 'min_child_weight', 'missing', 'monotone_constraints', 'n_estimators', 'n_jobs', 'num_parallel_tree', 'predictor', 'random_state', 'reg_alpha', 'reg_lambda', 'sampling_method', 'scale_pos_weight', 'subsample', 'tree_method', 'validate_parameters', 'verbosity'])